baseURL = "https://ie.u-ryukyu.ac.jp/e225719"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true

title = "Gale website"
copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Gale"
  headline = "全日本大学ストリートダンス沖縄連盟"
  image = "gale.jpeg"  # path relative to static directory

  links = [
    { link = { href = "https://docs.google.com/forms/d/e/1FAIpQLSevQkHeW65uBYNWIJgaNpAp6qALJ53UEFvq3SlDNawGPK1Tcg/viewform", text = "第3回 Gale道場 エントリーフォーム" } },
    { link = { href = "https://player-license.jusdl.or.jp/players/sign_in", text = "Jusdl Sign in" } },
    { instagram = { href = "https://instagram.com/jusdl_okinawa.gale", text = "instagram" } },
    { youtube = { href = "https://www.youtube.com/@jusdl_gale", text = "youtube" } },
    { email = { href = "mailto:e225719@ie.u-ryukyu.ac.jp?subject=Question", text = "email" } },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
